### ISSUE TITLE
Sample .srt file for captions

### ISSUE THREAD

**Issue by kthull** [MidCamp/live-captioning#1]
I actually read through most of this talk in a text editor.
[An External Design System in Practice.srt.zip](https://github.com/MidCamp/live-captioning/files/3096349/An.External.Design.System.in.Practice.srt.zip)

**Comment by kthull** [comment]
These are `.srt` file extensions but opened very legibly in a text editor. Example code below:
```1
00:00:00,159 --> 00:00:02,040
- [Brian] Hey everybody!

2
00:00:02,040 --> 00:00:05,730
This is an external
design system in practice.

3
00:00:05,730 --> 00:00:07,770
Hopefully you're in the right place.

4
00:00:07,770 --> 00:00:09,310
If not, we can just take the chairs

5
00:00:09,310 --> 00:00:10,845
that we put out and put them back.

6
00:00:10,845 --> 00:00:13,095
(laughter)

7
00:00:14,532 --> 00:00:15,365
I am Brian Perry.

8
00:00:15,365 --> 00:00:18,470
I'm a lead front end
developer at Bounteous.

9
00:00:18,470 --> 00:00:20,110
I live in the Chicago suburbs,

10
00:00:20,110 --> 00:00:21,520
which is more relevant to say

11
00:00:21,520 --> 00:00:23,980
when you are speaking at other camps.

12
00:00:23,980 --> 00:00:25,785
Substantially less interesting here.```

**Comment by kthull** [comment]
Interesting to note that the line breaks are actually picked up in the captions. IIRC, it was also about 6 different dialogs to upload a single file...I want to say I counted 12 total clicks per. Sort of a pain, but I'm sure the interface will improve.

**Comment by JDDoesDev** [comment]
Was this generated by our live captioning app or is this from the captioning that happened post camp?

**Comment by kthull** [comment]
This was post-event. Note that I did have to replace YouTube's auto captions (which I guess they do by default now?) with these files.

**Comment by andrewolson** [comment]
The project has been updated to capture the text in SRT format or plain text. Thanks @kthull for the example code for SRT! It was very helpful.
