### ISSUE TITLE
Add Google Analytics to the Jekyll Site

### ISSUE THREAD

**Issue by qymanab** [MidCamp/live-captioning#11]
Review:
https://michaelsoolee.com/google-analytics-jekyll/
https://desiredpersona.com/google-analytics-jekyll/
https://github.com/hendrikschneider/jekyll-analytics 

Add andrew "at" ozonedesign "dot" com for the Analytics account.

**Comment by andrewolson** [comment]
Closing this issue. It was completed in March 2020.
