### ISSUE TITLE
Add transcripts from MidCamp 2019 to the MidCamp.org website.

### ISSUE THREAD

**Issue by andrewolson** [MidCamp/live-captioning#12]

**Comment by mcdwayne** [comment]
Added all the captions from the .srt files I was given by Andrew. These are the sessions done so far:

1. Visual Regression Testing with BackstopJS
2. Understanding migration development in Drupal 8: Strategies and tools to see what's happening
3. Principles of Unit Testing
4. Level Up Your Drupal 8 Configuration Management
5. Keynote Session: Actions Speak Louder than Code
6. Federated Search with Drupal, Solr, and React
7. Everything I know about Kubernetes I learned from a cluster of Raspberry Pis
8. Empathy for internal users: Build and train for real content admins
9. Delivering Headless Commerce
10. Beyond Herding Cats: Lessons for Project Management in a Small Agency
11. An Introduction to Static Site Generators for Drupalists and Static Site Show and Tell
12. An External Design System in Practice
13. Amazing Emails from Drupal 8
14. A Modern Designer's Workflow
15. Ace any design in Drupal - layout tools and components in your site-building toolbox

**Comment by mcdwayne** [comment]
Updated all of the 2019 vids on the site to include transcripts and removed feedback form

Note: There are 57 total videos in the playlist but only 55 sessions listed below. One of them is the Lullabot training which is 4 hours long and the other is Energizing the Seated, which is not a published node, as it is the first half of Erasing the Stigma & Energizing the Seated

Full list of all sessions modified:

1. A Chirping Colorful Review of Web Design Usage
2. A Modern Designer's Workflow
3. Accessibility for Project Managers
4. Ace any design in Drupal - layout tools and components in your site-building toolbox
5. Adoptable Goats Near Me: What I Googled the Year I Became a Developer
6. Adopting a Drupal Contrib-First Approach
7. Amazing Emails from Drupal 8
8. An External Design System in Practice
9. An Introduction to Gulp
10. An Introduction to Static Site Generators for Drupalists and Static Site Show and Tell
11. Anonymous Personalization Without Leaving Drupal
12. Audit Your Theme
13. Backdrop CMS: past and future
14. Beyond Herding Cats: Lessons for Project Management in a Small Agency
15. Community Working Group Update and Q&A
16. Composer 101
17. Data Visualization in Drupal
18. Delivering Headless Commerce
19. Designing Accessible Sign Up Forms
20. Digital Well-Being: If you need to resort to alert fatigue, you’re designing it wrong.
21. Effective Cross-Functional Communication
22. Empathy for internal users: Build and train for real content admins
23. Erasing the Stigma
24. Erasing the Stigma & Energizing the Seated
25. Event Organizers Panel
26. Everything I know about Kubernetes I learned from a cluster of Raspberry Pis
27. Federated Search with Drupal, Solr, and React
28. Feeds UI + Migrate Engine = Dream Migrations and Imports
29. Hosting Drupal on AWS
30. How to give a Drupal Camp talk!
31. How to Hire and Fire Your Employer
32. Inclusive Content Strategy
33. Intro to Views - Creating Dynamic Lists of Content
34. Iterative UX: Find It Cambridge Case Study
35. Keynote Session: Actions Speak Louder than Code
36. Level Up Your Development Experience with Lando
37. Level Up Your Drupal 8 Configuration Management
38. Lost on an Island: Building Remote Collaboration in Cross-Continent Distributed Teams
39. Make Drupal 7 Development Fun and Modern
40. Maximum PhpStorm
41. My Ambitious Experience with Drupal 8; the Rest is History
42. Pantheon's Guide to Security in Higher Ed and Beyond
43. Personal Internet Security Basics
44. Practical Ways to Include people with disabilities in design
45. Preprocessing Paragraphs: A Beginner's Guide
46. Principles of Unit Testing
47. SimplyTest.me - A community case study
48. Stay Hungry. An appetite for New Business
49. Taking Drupal Commerce to Market: 2019 Roadmap
50. The Curmudgeon's Guide to Building Drupal Websites
51. Understanding migration development in Drupal 8: Strategies and tools to see what's happening
52. Visual Regression Testing with BackstopJS
53. Where is my next project coming from? Sales pipeline management for freelancers and small agencies
54. You Are Here: Exploring the Most Magical CMS on Earth
55. Overcoming Imposter Syndrome: How Weightlifting Helped Me Accept My Place in Tech
